export type ProductCategory = "anime" | "jeux" | "rgb" | "standard" | "bureautique";
export type ProductSize = "S" | "M" | "L" | "XL" | "XXL" | "XXXL";

export interface Product {
  id: string;
  slug: string;
  name: string;
  shortName: string;
  price: number;
  originalPrice?: number;
  category: ProductCategory;
  subCategory: string;
  size: ProductSize;
  dimensions: string;
  gradient: string;
  accentColor: string;
  rating: number;
  reviews: number;
  badge?: string;
  description: string;
  images?: string[];
  features: string[];
  isNew?: boolean;
  isBestSeller?: boolean;
  isRGB?: boolean;
  stock: number;
}

export const PRODUCTS: Product[] = [
  // ── ANIME ──────────────────────────────────────────────────────────────────
  {
    id: "dbz-goku-xl",
    slug: "tapis-dragon-ball-z-goku-xl",
    name: "Tapis Gaming Dragon Ball Z — Goku Ultra Instinct",
    shortName: "DBZ Goku Ultra Instinct",
    price: 19.99,
    category: "anime",
    subCategory: "dragon-ball",
    size: "XL",
    dimensions: "80 × 30 cm",
    gradient: "linear-gradient(135deg, #ff6600 0%, #ffd700 40%, #ff9900 70%, #cc4400 100%)",
    accentColor: "#ff9900",
    rating: 4.8,
    reviews: 5,
    badge: "BEST-SELLER",
    description: "Tapis gaming premium Dragon Ball Z avec impression Ultra HD résistante à l'eau. Anti-dérapant haute qualité, bords cousus.",
    features: ["Impression Ultra HD", "Anti-dérapant", "Bords cousus", "Résistant eau"],
    isBestSeller: true,
    stock: 43,
  },
  {
    id: "dbz-vegeta-xxl",
    slug: "tapis-dragon-ball-z-vegeta-xxl",
    name: "Tapis Gaming Dragon Ball Z — Vegeta Super Saiyan",
    shortName: "DBZ Vegeta SSJ",
    price: 22.99,
    category: "anime",
    subCategory: "dragon-ball",
    size: "XXL",
    dimensions: "90 × 40 cm",
    gradient: "linear-gradient(135deg, #1a0033 0%, #660099 40%, #ff0066 70%, #330066 100%)",
    accentColor: "#9900ff",
    rating: 4.6,
    reviews: 5,
    description: "Immense tapis Vegeta en pleine transformation. Surface lisse idéale pour les mouvements précis.",
    features: ["Surface micro-texturée", "Mousse 3mm", "Bords surpiqués", "Waterproof"],
    isNew: true,
    stock: 28,
  },
  {
    id: "naruto-sage-xl",
    slug: "tapis-naruto-mode-sage-xl",
    name: "Tapis Gaming Naruto — Mode Sage des Six Voies",
    shortName: "Naruto Sage Mode",
    price: 18.99,
    category: "anime",
    subCategory: "naruto",
    size: "XL",
    dimensions: "80 × 30 cm",
    gradient: "linear-gradient(135deg, #ff4500 0%, #ff8c00 30%, #ffd700 60%, #cc3300 100%)",
    accentColor: "#ff4500",
    rating: 4.7,
    reviews: 6,
    badge: "POPULAIRE",
    description: "Naruto en mode sage des six voies sur fond épique. Qualité premium pour les vrais fans.",
    features: ["Impression HD durable", "Anti-dérapant renforcé", "Bords cousus", "Lavable"],
    stock: 67,
  },
  {
    id: "naruto-akatsuki-xxl",
    slug: "tapis-naruto-akatsuki-xxl",
    name: "Tapis Gaming Naruto — Akatsuki XXL",
    shortName: "Naruto Akatsuki",
    price: 22.99,
    category: "anime",
    subCategory: "naruto",
    size: "XXL",
    dimensions: "90 × 40 cm",
    gradient: "linear-gradient(135deg, #0a0a0a 0%, #8b0000 40%, #ff0000 60%, #1a0000 100%)",
    accentColor: "#cc0000",
    rating: 4.5,
    reviews: 4,
    description: "Les nuages rouges Akatsuki sur fond noir — le tapis parfait pour imposer ton territoire.",
    features: ["Fond noir intense", "Bords cousus or", "3mm épaisseur", "Anti-poussière"],
    stock: 22,
  },
  {
    id: "op-gear5-xl",
    slug: "tapis-one-piece-gear-5-xl",
    name: "Tapis Gaming One Piece — Luffy Gear 5",
    shortName: "One Piece Gear 5",
    price: 19.99,
    category: "anime",
    subCategory: "one-piece",
    size: "XL",
    dimensions: "80 × 30 cm",
    gradient: "linear-gradient(135deg, #fff8e1 0%, #ffd700 30%, #ff4500 60%, #cc0000 100%)",
    accentColor: "#ffd700",
    rating: 4.8,
    reviews: 4,
    badge: "NOUVEAU",
    description: "Le mythique Gear 5 de Monkey D. Luffy dans toute sa gloire. Impression photorealiste.",
    features: ["Impression photorealiste", "Surface speed-control", "Rubber base", "Bords cousus"],
    images: ["/products/one-piece-1.png", "/products/one-piece-1-1.png"],
    isNew: true,
    isBestSeller: true,
    stock: 55,
  },
  {
    id: "demonslayer-tanjiro-l",
    slug: "tapis-demon-slayer-tanjiro-l",
    name: "Tapis Gaming Demon Slayer — Tanjiro Souffle de l'Eau",
    shortName: "Demon Slayer Tanjiro",
    price: 16.99,
    category: "anime",
    subCategory: "demon-slayer",
    size: "L",
    dimensions: "60 × 30 cm",
    gradient: "linear-gradient(135deg, #001a33 0%, #003366 30%, #0066cc 60%, #00aaff 100%)",
    accentColor: "#00aaff",
    rating: 4.6,
    reviews: 5,
    description: "Les flammes aqueuses enveloppent Tanjiro dans cette illustration épique. Couleurs intenses.",
    features: ["Couleurs UV résistantes", "Base antidérapante", "60x30cm", "Bords renforcés"],
    stock: 38,
  },
  {
    id: "aot-survey-xxl",
    slug: "tapis-attack-on-titan-survey-corps-xxl",
    name: "Tapis Gaming Attack on Titan — Survey Corps",
    shortName: "AoT Survey Corps",
    price: 22.99,
    category: "anime",
    subCategory: "attack-on-titan",
    size: "XXL",
    dimensions: "90 × 40 cm",
    gradient: "linear-gradient(135deg, #2d4a2d 0%, #4a6b3a 30%, #8b7355 60%, #3d2a1a 100%)",
    accentColor: "#8b7355",
    rating: 4.7,
    reviews: 3,
    description: "Les Titans et le Corps de Reconnaissance immortalisés sur ce tapis XXL impressionnant.",
    features: ["Format XXL", "Impression panoramique", "Base 5mm", "Bords cousus"],
    stock: 15,
  },
  {
    id: "jjk-gojo-xxl",
    slug: "tapis-jujutsu-kaisen-gojo-xxl",
    name: "Tapis Gaming Jujutsu Kaisen — Gojo Six Yeux",
    shortName: "JJK Gojo Satoru",
    price: 23.99,
    category: "anime",
    subCategory: "jujutsu-kaisen",
    size: "XXL",
    dimensions: "90 × 40 cm",
    gradient: "linear-gradient(135deg, #000066 0%, #0000cc 30%, #6666ff 60%, #ffffff 100%)",
    accentColor: "#6666ff",
    rating: 4.8,
    reviews: 5,
    badge: "TOP VENTE",
    description: "Gojo Satoru ouvre les yeux. Le tapis le plus demandé du moment. Édition premium.",
    features: ["Édition premium", "Infini pattern", "Base velours", "Bords brodés"],
    isBestSeller: true,
    stock: 8,
  },

  // ── JEUX ──────────────────────────────────────────────────────────────────
  {
    id: "lol-jinx-xl",
    slug: "tapis-league-of-legends-jinx-xl",
    name: "Tapis Gaming League of Legends — Jinx Arcane",
    shortName: "LoL Jinx Arcane",
    price: 19.99,
    category: "jeux",
    subCategory: "league-of-legends",
    size: "XL",
    dimensions: "80 × 30 cm",
    gradient: "linear-gradient(135deg, #0a1628 0%, #1e3a5f 30%, #00c8ff 60%, #ff69b4 100%)",
    accentColor: "#00c8ff",
    rating: 4.6,
    reviews: 5,
    badge: "POPULAIRE",
    description: "Jinx en version Arcane sur ce tapis gamer XL ultra précis. Parfait pour les rankeds.",
    features: ["Surface speed", "Base anti-glisse", "XL 80x30cm", "Waterproof"],
    stock: 52,
  },
  {
    id: "valorant-agents-xxl",
    slug: "tapis-valorant-agents-xxl",
    name: "Tapis Gaming Valorant — Roster Agents",
    shortName: "Valorant All Agents",
    price: 22.99,
    category: "jeux",
    subCategory: "valorant",
    size: "XXL",
    dimensions: "90 × 40 cm",
    gradient: "linear-gradient(135deg, #1a0000 0%, #cc0000 30%, #ff4040 60%, #ff8800 100%)",
    accentColor: "#ff4040",
    rating: 4.8,
    reviews: 6,
    badge: "BEST-SELLER",
    description: "Tous les agents Valorant alignés. Le tapis des vrais Radiant. Surface Control idéale.",
    features: ["Surface Control", "22 agents", "Base 4mm", "Bords rouges cousus"],
    isBestSeller: true,
    stock: 74,
  },
  {
    id: "cs2-dust2-xl",
    slug: "tapis-cs2-dust2-xl",
    name: "Tapis Gaming CS2 — Dust 2 Map",
    shortName: "CS2 Dust 2",
    price: 18.99,
    category: "jeux",
    subCategory: "cs2",
    size: "XL",
    dimensions: "80 × 30 cm",
    gradient: "linear-gradient(135deg, #c8a870 0%, #a07840 30%, #806030 60%, #604820 100%)",
    accentColor: "#c8a870",
    rating: 4.5,
    reviews: 4,
    description: "La map la plus iconique du FPS sur ton bureau. Connais chaque angle même à ton desk.",
    features: ["Map HD", "Anti-dérapant", "Bords cousus", "Format XL"],
    stock: 31,
  },
  {
    id: "fortnite-victory-xl",
    slug: "tapis-fortnite-victory-royale-xl",
    name: "Tapis Gaming Fortnite — Victory Royale",
    shortName: "Fortnite Victory Royale",
    price: 16.99,
    category: "jeux",
    subCategory: "fortnite",
    size: "XL",
    dimensions: "80 × 30 cm",
    gradient: "linear-gradient(135deg, #003399 0%, #0066ff 30%, #9933ff 60%, #ff6600 100%)",
    accentColor: "#9933ff",
    rating: 4.5,
    reviews: 4,
    badge: "POPULAIRE",
    description: "Le célèbre Victory Royale sur un fond de storm épique. Impression Ultra HD, anti-dérapant renforcé. Pour les 1ers emplacements.",
    features: ["Couleurs vives", "Impression Ultra HD", "Anti-friction", "Base rubber", "Bords cousus", "Résistant eau"],
    stock: 48,
    images: [
      "/images/produits/fortnite/fortnite-1.jpg",
      "/images/produits/fortnite/fortnite-2.jpg",
      "/images/produits/fortnite/fortnite-3.jpg",
      "/images/produits/fortnite/fortnite-4.jpg",
      "/images/produits/fortnite/fortnite-5.jpg",
      "/images/produits/fortnite/fortnite-6.jpg",
      "/images/produits/fortnite/fortnite-7.jpg",
    ],
  },
  {
    id: "apex-legends-xxl",
    slug: "tapis-apex-legends-xxl",
    name: "Tapis Gaming Apex Legends — Legends XXL",
    shortName: "Apex Legends",
    price: 22.99,
    category: "jeux",
    subCategory: "apex-legends",
    size: "XXL",
    dimensions: "90 × 40 cm",
    gradient: "linear-gradient(135deg, #cc4400 0%, #ff6600 30%, #ffaa00 60%, #cc2200 100%)",
    accentColor: "#ff6600",
    rating: 4.7,
    reviews: 3,
    isNew: true,
    description: "Tous les legends dans le ring. Format XXL pour poser clavier + souris. Champion vibes.",
    features: ["XXL format", "Texture grip", "Impression DPI", "Bords orange cousus"],
    stock: 19,
  },

  // ── RGB ───────────────────────────────────────────────────────────────────
  {
    id: "rgb-geo-elite-xl",
    slug: "tapis-rgb-geometrique-elite-xl",
    name: "Tapis RGB Géométrique Elite — Édition Obsidian XL",
    shortName: "RGB Géo Elite XL",
    price: 29.99,
    category: "rgb",
    subCategory: "rgb-fulldesk",
    size: "XL",
    dimensions: "80 × 30 cm",
    gradient: "linear-gradient(135deg, #050810 0%, #0a0f1a 50%, #0d1525 100%)",
    accentColor: "#00e5ff",
    rating: 4.8,
    reviews: 5,
    badge: "RGB LED",
    description: "Surface noire géométrique cristal avec bordure LED RGB cyan ultra-lumineuse. 7 modes d'éclairage. Compatible tous setups gaming. Alimenté USB, plug & play.",
    features: ["Bordure LED 16.8M couleurs", "7 modes RGB", "Surface cristal géométrique", "USB plug & play", "Base antidérapante"],
    images: ["/products/rgb-xl-setup.jpg", "/products/rgb-xl-closeup.jpg"],
    isRGB: true,
    isNew: true,
    isBestSeller: true,
    stock: 47,
  },
  {
    id: "rgb-dbz-xl",
    slug: "tapis-rgb-dragon-ball-z-xl",
    name: "Tapis RGB LED Dragon Ball Z — Collector",
    shortName: "RGB DBZ LED",
    price: 32.99,
    category: "rgb",
    subCategory: "rgb-anime",
    size: "XL",
    dimensions: "80 × 30 cm",
    gradient: "linear-gradient(135deg, #ff6600, #ffd700, #ff0066, #00e5ff, #00ff99, #bf00ff)",
    accentColor: "#00e5ff",
    rating: 4.8,
    reviews: 5,
    badge: "RGB LED",
    description: "Tapis Dragon Ball Z avec bordure LED RGB 16.8M couleurs. 7 effets lumineux. USB alimenté.",
    features: ["16.8M couleurs LED", "7 effets RGB", "USB powered", "Contrôleur inclus"],
    isRGB: true,
    isBestSeller: true,
    stock: 34,
  },
  {
    id: "rgb-valorant-xxl",
    slug: "tapis-rgb-valorant-xxl",
    name: "Tapis RGB LED Valorant — Pro Edition XXL",
    shortName: "RGB Valorant PRO",
    price: 34.99,
    category: "rgb",
    subCategory: "rgb-jeux",
    size: "XXL",
    dimensions: "90 × 40 cm",
    gradient: "linear-gradient(135deg, #ff0066, #ff4444, #00e5ff, #00ff99, #bf00ff)",
    accentColor: "#ff0066",
    rating: 4.8,
    reviews: 4,
    badge: "RGB LED",
    description: "Le plus grand tapis RGB Valorant avec 14 zones LED indépendantes. Synchronisation avec Synapse.",
    features: ["14 zones LED", "Synapse compatible", "USB-C", "Extra-large format"],
    isRGB: true,
    stock: 21,
  },
  {
    id: "rgb-fulldesk-xxxl",
    slug: "tapis-rgb-full-desk-xxxl",
    name: "Tapis RGB Full Desk — Intégral XXXL",
    shortName: "RGB Full Desk XXXL",
    price: 39.99,
    category: "rgb",
    subCategory: "rgb-fulldesk",
    size: "XXXL",
    dimensions: "120 × 60 cm",
    gradient: "linear-gradient(135deg, #020209, #00e5ff 20%, #ff0066 40%, #00ff99 60%, #bf00ff 80%, #020209)",
    accentColor: "#00e5ff",
    rating: 4.8,
    reviews: 4,
    badge: "PREMIUM RGB",
    description: "Couvre intégralement ton bureau. RGB 360° sur 4 côtés. Le setup ultime des pros.",
    features: ["4 côtés RGB", "120x60cm", "Waterproof", "USB-C 2m tressé"],
    isRGB: true,
    isBestSeller: true,
    stock: 12,
  },

  // ── BUREAUTIQUE ───────────────────────────────────────────────────────────
  {
    id: "bureau-minimaliste-xl",
    slug: "tapis-bureautique-minimaliste-xl",
    name: "Tapis de Bureau Minimaliste — Noir Uni XL",
    shortName: "Minimaliste Noir",
    price: 14.99,
    category: "bureautique",
    subCategory: "minimaliste",
    size: "XL",
    dimensions: "80 × 30 cm",
    gradient: "linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 50%, #0f0f0f 100%)",
    accentColor: "#ffffff",
    rating: 4.6,
    reviews: 5,
    badge: "POPULAIRE",
    description: "Tapis de bureau épuré, noir mat premium. Surface douce pour une utilisation quotidienne prolongée.",
    features: ["Surface douce", "Anti-dérapant", "Lavable", "Bords cousus"],
    isNew: false,
    isBestSeller: true,
    stock: 80,
  },
  {
    id: "bureau-cuir-l",
    slug: "tapis-bureautique-effet-cuir-l",
    name: "Tapis de Bureau Effet Cuir — Marron Large",
    shortName: "Effet Cuir Marron",
    price: 16.99,
    category: "bureautique",
    subCategory: "cuir",
    size: "L",
    dimensions: "60 × 30 cm",
    gradient: "linear-gradient(135deg, #3b1f0a 0%, #6b3a1f 40%, #4a2810 100%)",
    accentColor: "#c8883a",
    rating: 4.8,
    reviews: 4,
    description: "Aspect cuir haut de gamme pour un bureau élégant. Idéal pour les environnements professionnels.",
    features: ["Effet cuir premium", "Ultra doux", "Base antidérapante", "Waterproof"],
    isNew: true,
    stock: 45,
  },
  {
    id: "bureau-nature-xxl",
    slug: "tapis-bureautique-nature-xxl",
    name: "Tapis de Bureau Nature — Bois & Feuilles XXL",
    shortName: "Nature Bois",
    price: 19.99,
    category: "bureautique",
    subCategory: "nature",
    size: "XXL",
    dimensions: "90 × 40 cm",
    gradient: "linear-gradient(135deg, #1a2e1a 0%, #2d4a20 40%, #3d6030 100%)",
    accentColor: "#6abf5e",
    rating: 4.7,
    reviews: 3,
    badge: "NOUVEAU",
    description: "Motifs naturels apaisants pour un bureau zen. Texture douce, parfait pour de longues sessions de travail.",
    features: ["Motif nature HD", "Surface veloutée", "Bords surpiqués", "Anti-fatigue"],
    isNew: true,
    stock: 33,
  },
  {
    id: "bureau-marbre-xl",
    slug: "tapis-bureautique-marbre-blanc-xl",
    name: "Tapis de Bureau Marbre Blanc — Élégance XL",
    shortName: "Marbre Blanc",
    price: 15.99,
    category: "bureautique",
    subCategory: "marbre",
    size: "XL",
    dimensions: "80 × 30 cm",
    gradient: "linear-gradient(135deg, #e8e8e8 0%, #f5f5f5 30%, #d0d0d0 60%, #e0e0e0 100%)",
    accentColor: "#aaaaaa",
    rating: 4.8,
    reviews: 5,
    badge: "TOP VENTE",
    description: "Design marbre blanc sobre et luxueux. Parfait pour un setup moderne et épuré.",
    features: ["Marbre HD", "Surface lisse", "Base rubber", "Facile à nettoyer"],
    isBestSeller: true,
    stock: 58,
  },
  {
    id: "bureau-gradient-m",
    slug: "tapis-bureautique-gradient-pastel-m",
    name: "Tapis de Bureau Dégradé Pastel — Medium",
    shortName: "Dégradé Pastel",
    price: 11.99,
    category: "bureautique",
    subCategory: "couleur",
    size: "M",
    dimensions: "40 × 30 cm",
    gradient: "linear-gradient(135deg, #ffd6e0 0%, #c9b8f5 40%, #b8e0ff 100%)",
    accentColor: "#c9b8f5",
    rating: 4.4,
    reviews: 5,
    description: "Dégradé pastel doux pour un espace de travail coloré et inspirant. Format idéal pour laptop.",
    features: ["Pastel HD", "Format laptop", "Anti-dérapant", "Bords cousus"],
    isNew: true,
    stock: 72,
  },

  // ── STANDARD (par taille) ─────────────────────────────────────────────────
  {
    id: "std-s",
    slug: "tapis-gaming-standard-s",
    name: "Tapis Gaming Standard — Small",
    shortName: "Standard S",
    price: 7.99,
    category: "standard",
    subCategory: "tailles",
    size: "S",
    dimensions: "25 × 20 cm",
    gradient: "linear-gradient(135deg, #0d0d1a 0%, #1a1a33 50%, #0d0d1a 100%)",
    accentColor: "#00e5ff",
    rating: 4.3,
    reviews: 3,
    description: "Tapis gaming compact pour setup minimaliste. Surface lisse pour les mouvements rapides.",
    features: ["Ultra compact", "Surface speed", "Facile à transporter", "Anti-dérapant"],
    stock: 120,
  },
  {
    id: "std-m",
    slug: "tapis-gaming-standard-m",
    name: "Tapis Gaming Standard — Medium",
    shortName: "Standard M",
    price: 11.99,
    category: "standard",
    subCategory: "tailles",
    size: "M",
    dimensions: "40 × 30 cm",
    gradient: "linear-gradient(135deg, #0d0d1a 0%, #1a1a33 50%, #0d0d1a 100%)",
    accentColor: "#00e5ff",
    rating: 4.3,
    reviews: 3,
    description: "Le format medium idéal pour la plupart des setups. Équilibre parfait taille/prix.",
    features: ["Format idéal", "Surface precision", "Base 3mm", "Bords cousus"],
    stock: 85,
  },
  {
    id: "std-l",
    slug: "tapis-gaming-standard-l",
    name: "Tapis Gaming Standard — Large",
    shortName: "Standard L",
    price: 14.99,
    category: "standard",
    subCategory: "tailles",
    size: "L",
    dimensions: "60 × 30 cm",
    gradient: "linear-gradient(135deg, #0d0d1a 0%, #1a1a33 50%, #0d0d1a 100%)",
    accentColor: "#00e5ff",
    rating: 4.5,
    reviews: 4,
    description: "Grand format pour clavier + souris. Confort optimal pour les longues sessions.",
    features: ["Clavier + souris", "Confort longue durée", "Base 4mm", "Anti-fatigue"],
    stock: 62,
  },
  {
    id: "std-xl",
    slug: "tapis-gaming-standard-xl",
    name: "Tapis Gaming Standard — Extra Large",
    shortName: "Standard XL",
    price: 17.99,
    category: "standard",
    subCategory: "tailles",
    size: "XL",
    dimensions: "80 × 30 cm",
    gradient: "linear-gradient(135deg, #0d0d1a 0%, #1a1a33 50%, #0d0d1a 100%)",
    accentColor: "#00e5ff",
    rating: 4.6,
    reviews: 5,
    description: "XL pour un vrai setup gamer. Assez grand pour les souris haute DPI en faible sensibilité.",
    features: ["Low sens friendly", "Surface speed", "Base 4mm", "Bords renforcés"],
    stock: 44,
  },
  {
    id: "std-xxxl",
    slug: "tapis-gaming-standard-xxxl",
    name: "Tapis Gaming Full Desk — XXXL",
    shortName: "Full Desk XXXL",
    price: 27.99,
    category: "standard",
    subCategory: "tailles",
    size: "XXXL",
    dimensions: "120 × 60 cm",
    gradient: "linear-gradient(135deg, #0d0d1a 0%, #1a1a33 50%, #0d0d1a 100%)",
    accentColor: "#00e5ff",
    rating: 4.8,
    reviews: 4,
    badge: "FULL DESK",
    description: "Couvre l'intégralité de ton bureau. Le saint graal du setup gamer.",
    features: ["Full Desk coverage", "Ultra stable", "5mm épaisseur", "Imperméable"],
    stock: 23,
  },
];

export const ANIME_CATEGORIES = [
  { slug: "dragon-ball", name: "Dragon Ball Z", color: "#ff9900", count: PRODUCTS.filter(p => p.subCategory === "dragon-ball").length },
  { slug: "naruto", name: "Naruto", color: "#ff4500", count: PRODUCTS.filter(p => p.subCategory === "naruto").length },
  { slug: "one-piece", name: "One Piece", color: "#ffd700", count: PRODUCTS.filter(p => p.subCategory === "one-piece").length },
  { slug: "demon-slayer", name: "Demon Slayer", color: "#00aaff", count: PRODUCTS.filter(p => p.subCategory === "demon-slayer").length },
  { slug: "attack-on-titan", name: "Attack on Titan", color: "#8b7355", count: PRODUCTS.filter(p => p.subCategory === "attack-on-titan").length },
  { slug: "jujutsu-kaisen", name: "Jujutsu Kaisen", color: "#6666ff", count: PRODUCTS.filter(p => p.subCategory === "jujutsu-kaisen").length },
];

export const GAME_CATEGORIES = [
  { slug: "league-of-legends", name: "League of Legends", color: "#c89b3c", count: PRODUCTS.filter(p => p.subCategory === "league-of-legends").length },
  { slug: "valorant", name: "Valorant", color: "#ff4040", count: PRODUCTS.filter(p => p.subCategory === "valorant").length },
  { slug: "cs2", name: "Counter-Strike 2", color: "#f0a000", count: PRODUCTS.filter(p => p.subCategory === "cs2").length },
  { slug: "fortnite", name: "Fortnite", color: "#9933ff", count: PRODUCTS.filter(p => p.subCategory === "fortnite").length },
  { slug: "apex-legends", name: "Apex Legends", color: "#ff6600", count: PRODUCTS.filter(p => p.subCategory === "apex-legends").length },
];

export const BUREAU_CATEGORIES = [
  { slug: "minimaliste", name: "Minimaliste", color: "#ffffff", count: PRODUCTS.filter(p => p.subCategory === "minimaliste").length },
  { slug: "cuir", name: "Effet Cuir", color: "#c8883a", count: PRODUCTS.filter(p => p.subCategory === "cuir").length },
  { slug: "nature", name: "Nature", color: "#6abf5e", count: PRODUCTS.filter(p => p.subCategory === "nature").length },
  { slug: "marbre", name: "Marbre", color: "#aaaaaa", count: PRODUCTS.filter(p => p.subCategory === "marbre").length },
  { slug: "couleur", name: "Couleurs & Dégradés", color: "#c9b8f5", count: PRODUCTS.filter(p => p.subCategory === "couleur").length },
];

export const SIZE_CATEGORIES = [
  { slug: "s", label: "Small", dimensions: "25 × 20 cm", icon: "S", desc: "Format compact" },
  { slug: "m", label: "Medium", dimensions: "40 × 30 cm", icon: "M", desc: "Format standard" },
  { slug: "l", label: "Large", dimensions: "60 × 30 cm", icon: "L", desc: "Clavier + souris" },
  { slug: "xl", label: "Extra Large", dimensions: "80 × 30 cm", icon: "XL", desc: "Gamer XL" },
  { slug: "xxl", label: "XXL", dimensions: "90 × 40 cm", icon: "XXL", desc: "Double espace" },
  { slug: "xxxl", label: "Full Desk", dimensions: "120 × 60 cm", icon: "XXXL", desc: "Bureau entier" },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find(p => p.slug === slug);
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return PRODUCTS.filter(p => p.category === category);
}

export function getProductsBySubCategory(subCategory: string): Product[] {
  return PRODUCTS.filter(p => p.subCategory === subCategory);
}

export function getProductsBySize(size: string): Product[] {
  return PRODUCTS.filter(p => p.size === size.toUpperCase());
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter(p => p.isBestSeller || p.isNew).slice(0, 8);
}
